name: BuildAndDeployApp

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CREATE_APP_NAME: my-first-app-name-12345
  DUO_ENABLE: 0
  GIT_HASH: master
jobs:
  create_and_deploy_app:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: stable
        # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: git checkout HEAD^
    - run: curl https://cli-assets.heroku.com/install.sh | sh
    - run: apt update && apt install jq openssl -y
    - run: bash create_bitwarden_app.sh -a $CREATE_APP_NAME -d $DUO_ENABLE -g $GIT_HASH